version: '3'
services:
  eosio:
    image: eosio/eos:v1.4.2
    container_name: eosio-sample
    command: bash -c "keosd --http-server-address=0.0.0.0:5555 & exec nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:7777 --access-control-allow-origin=* --contracts-console --http-validate-host=false --filter-on='*'"
    volumes:
      - ./build/contracts:/contracts
    ports:
      - "7777:7777"
      - "127.0.0.1:5555:5555"